[project]
name = "ilivery"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Logan Grado", email = "logangrado@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "jsonnet>=0.20.0",
    "loggerado>=0.3.0",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "opensimplex>=0.4.5.1",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "psd-tools>=1.10.7",
    "pydantic>=2.10.6",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.1.2",
    "invoke>=2.2.0",
    "ipdb>=0.13.13",
    "ipython>=9.0.2",
    "pytest>=8.3.5",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.hooks.version]
path = "ilivery/_version.py"
template = '''
__version__ = "{version}"
'''

[tool.black]
line_length=120
exclude=".venv"
